# Generated by Django 2.2.3 on 2021-04-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choferes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('contraseña', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('contraseña', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('gold', models.BooleanField()),
                ('tarjeta_cod_seguridad', models.CharField(max_length=3)),
                ('tarjeta_fecha_vencimiento', models.DateField()),
                ('tarjeta_nombre_titular', models.CharField(max_length=40)),
                ('tarjeta_numero', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Combis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=15)),
                ('patente', models.CharField(max_length=10)),
                ('cant_asientos', models.IntegerField()),
                ('tipo', models.CharField(max_length=15)),
                ('chofer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=20)),
                ('nombre_ciudad', models.CharField(max_length=20)),
                ('obervaciones', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_origen', models.CharField(max_length=20)),
                ('ciudad_destino', models.CharField(max_length=20)),
                ('combi', models.IntegerField()),
                ('datos_adicionales', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
