# Generated by Django 2.2.3 on 2021-05-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tarjeta_cod_seguridad',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tarjeta_fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tarjeta_nombre_titular',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tarjeta_numero',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
