# Generated by Django 2.2.3 on 2021-06-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tuvo_coronavirus',
            new_name='los_clientes_que_tuvieron_coronavirus',
        ),
    ]
