# Generated by Django 2.2.3 on 2021-06-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_suspension', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_suspension',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fue_suspendido',
            field=models.ManyToManyField(to='Tablas.Suspendido'),
        ),
    ]
