# Generated by Django 2.2.3 on 2021-05-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('contenido', models.TextField(max_length=400)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentarios', to='Tablas.Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
