# Generated by Django 2.2.3 on 2021-06-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cantidad_de_caracteres_de_la_contraseña',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
