# Generated by Django 2.2.3 on 2021-06-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='nombre',
        ),
    ]
