# Generated by Django 2.2.3 on 2021-05-27 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compras', to='Tablas.Cliente')),
                ('productos', models.ManyToManyField(to='Tablas.Producto')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compras', to='Tablas.Viaje')),
            ],
        ),
    ]
