# Generated by Django 2.2.3 on 2021-04-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugares',
            old_name='obervaciones',
            new_name='observaciones',
        ),
    ]
