# Generated by Django 2.2.3 on 2021-06-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_cliente_cantidad_de_caracteres_de_la_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='Tablas.Viaje'),
        ),
        migrations.AlterField(
            model_name='compra_producto',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra_producto', to='Tablas.Compra'),
        ),
    ]
