# Generated by Django 2.2.3 on 2021-05-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_auto_20210521_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
    ]
