# Generated by Django 2.2.3 on 2021-05-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compras', to='Tablas.Cliente'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, to='Tablas.Producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compras', to='Tablas.Viaje'),
        ),
    ]
