# Generated by Django 2.2.3 on 2021-06-22 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_auto_20210621_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'chofer': None, 'cliente': None, 'is_staff': False}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chofer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
