# Generated by Django 2.2.3 on 2021-04-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_auto_20210421_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choferes',
            new_name='Chofer',
        ),
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Combis',
            new_name='Combi',
        ),
        migrations.RenameModel(
            old_name='Lugares',
            new_name='Lugar',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Rutas',
            new_name='Ruta',
        ),
        migrations.RenameModel(
            old_name='Viajes',
            new_name='Viaje',
        ),
    ]
