# Generated by Django 2.2.3 on 2021-04-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0003_auto_20210421_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={'verbose_name': 'chofer', 'verbose_name_plural': 'choferes'},
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name': 'lugar', 'verbose_name_plural': 'lugares'},
        ),
    ]
