# Generated by Django 2.2.3 on 2021-05-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0003_auto_20210527_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='asientos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
