# Generated by Django 2.2.3 on 2021-06-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0003_auto_20210603_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra_producto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra_producto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
