# Generated by Django 2.2.3 on 2021-05-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0003_auto_20210521_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
