# Generated by Django 2.2.3 on 2021-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0004_auto_20210521_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='gold',
            field=models.BooleanField(default=False),
        ),
    ]
