# Generated by Django 2.2.3 on 2021-05-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0004_auto_20210524_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_de_creacion',
            field=models.DateTimeField(),
        ),
    ]
