# Generated by Django 2.2.3 on 2021-04-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0004_auto_20210421_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='combi',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tablas.Chofer'),
        ),
        migrations.AlterField(
            model_name='combi',
            name='patente',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='ciudad_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudad_destino', to='Tablas.Lugar'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='ciudad_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudad_origen', to='Tablas.Lugar'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='combi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tablas.Combi'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tablas.Ruta'),
        ),
    ]
