# Generated by Django 2.2.3 on 2021-07-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0004_auto_20210702_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='asientos_vendidos',
            field=models.CharField(default='No hay asientos vendidos todavía', max_length=40),
        ),
        migrations.AddField(
            model_name='viaje',
            name='dinero_recaudado',
            field=models.IntegerField(default=0),
        ),
    ]
