# Generated by Django 2.2.3 on 2021-05-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0004_compra_asientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='productos',
        ),
        migrations.CreateModel(
            name='Compra_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compra_producto', to='Tablas.Compra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compra_producto', to='Tablas.Producto')),
            ],
        ),
    ]
