# Generated by Django 2.2.3 on 2021-07-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0005_auto_20210707_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='asientos_vendidos',
            new_name='asientos_vendidos_que_no_fueron_cancelados',
        ),
    ]
