# Generated by Django 2.2.3 on 2021-05-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0005_auto_20210524_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha',
        ),
    ]
