# Generated by Django 2.2.3 on 2021-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0005_auto_20210424_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('Cómoda', 'Cómoda'), ('Super-cómoda', 'Super-cómoda')], max_length=15),
        ),
    ]
