# Generated by Django 2.2.3 on 2021-04-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0007_auto_20210426_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('Cómoda', 'Cómoda'), ('Súper-cómoda', 'Súper-cómoda')], max_length=15),
        ),
    ]
