# Generated by Django 2.2.3 on 2021-04-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0008_auto_20210426_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='dni',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
