# Generated by Django 2.2.3 on 2021-04-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0009_chofer_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
