# Generated by Django 2.2.3 on 2021-04-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0012_auto_20210429_2235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('ciudad_origen', 'ciudad_destino')},
        ),
    ]
