# Generated by Django 2.2.3 on 2021-04-30 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0013_auto_20210429_2241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together={('ruta', 'fecha_hora')},
        ),
    ]
