# Generated by Django 2.2.3 on 2021-05-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0014_auto_20210429_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='observaciones',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='datos_adicionales',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
