# Generated by Django 2.2.3 on 2021-05-08 16:55

import Tablas.softdeletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0015_auto_20210507_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=20, validators=[Tablas.softdeletion.validar_dni_cliente]),
        ),
    ]
