# Generated by Django 2.2.3 on 2021-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0016_auto_20210508_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
