# Generated by Django 2.2.3 on 2021-05-08 20:19

import Tablas.softdeletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0017_cliente_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chofer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combi',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combi',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugar',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruta',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viaje',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='dni',
            field=models.CharField(max_length=20, validators=[Tablas.softdeletion.validar_dni_chofer]),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='email',
            field=models.EmailField(max_length=40, validators=[Tablas.softdeletion.validar_email_chofer]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=40, validators=[Tablas.softdeletion.validar_email_cliente]),
        ),
        migrations.AlterField(
            model_name='combi',
            name='patente',
            field=models.CharField(max_length=10, validators=[Tablas.softdeletion.validar_patente_combi]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=20, validators=[Tablas.softdeletion.validar_nombre_producto]),
        ),
    ]
