# Generated by Django 2.2.3 on 2021-05-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0018_auto_20210508_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='datos_adicionales',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
