# Generated by Django 2.2.3 on 2021-05-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0019_viaje_datos_adicionales'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lugar',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together=set(),
        ),
    ]
